import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const EXTERNALS = [
  "obsidian", "electron", "child_process", "fs", "path", "os", "crypto",
  "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands",
  "@codemirror/language", "@codemirror/lint", "@codemirror/search",
  "@codemirror/state", "@codemirror/view", "@lezer/common",
  "@lezer/highlight", "@lezer/lr", ...builtinModules,
];

const FDC_SOURCE = ".super_nutrition_ref/fdc-data.json";
const FDC_DEST = "fdc-data.json";
const FDC_MINI_DEST = "fdc-mini-index.json";

const buildOpts = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: EXTERNALS,
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  treeShaking: false,
  outfile: "main.js",
  minify: prod,
  sourcemap: prod ? false : "inline",
};

if (prod) {
  await esbuild.build(buildOpts);

  const fdcSource = fs.existsSync(FDC_SOURCE) ? FDC_SOURCE
    : fs.existsSync(FDC_DEST) ? FDC_DEST : null;

  if (fdcSource) {
    if (fdcSource !== FDC_DEST) fs.copyFileSync(fdcSource, FDC_DEST);
    console.log(`[build] FDC data: ${fdcSource} (${Math.round(fs.statSync(FDC_DEST).size / 1024)} KB)`);

    const fullData = JSON.parse(fs.readFileSync(FDC_DEST, "utf8"));
    const miniIndex = fullData.map(([name, nutrients]) => [
      name,
      { Energy: typeof nutrients["Energy"] === "number" ? nutrients["Energy"] : 0 },
    ]);
    fs.writeFileSync(FDC_MINI_DEST, JSON.stringify(miniIndex), "utf8");
    console.log(`[build] Generated FDC mini-index: ${miniIndex.length} items, ${Math.round(fs.statSync(FDC_MINI_DEST).size / 1024)} KB`);
  }

  const vaultCandidates = process.env.OBSIDIAN_VAULT
    ? [process.env.OBSIDIAN_VAULT]
    : [`${process.env.HOME}/Documents/Obsidian`];
  for (const vault of vaultCandidates) {
    if (!vault) continue;
    const pluginDir = path.join(vault, ".obsidian/plugins/pantryfin");
    if (fs.existsSync(pluginDir)) {
      fs.copyFileSync("main.js", path.join(pluginDir, "main.js"));
      if (fs.existsSync(FDC_DEST)) fs.copyFileSync(FDC_DEST, path.join(pluginDir, FDC_DEST));
      if (fs.existsSync(FDC_MINI_DEST)) fs.copyFileSync(FDC_MINI_DEST, path.join(pluginDir, FDC_MINI_DEST));
      if (fs.existsSync("manifest.json")) fs.copyFileSync("manifest.json", path.join(pluginDir, "manifest.json"));
      if (fs.existsSync("styles.css")) fs.copyFileSync("styles.css", path.join(pluginDir, "styles.css"));
      console.log(`[build] Synced to Obsidian: ${pluginDir}`);
    }
  }
  process.exit(0);
} else {
  const context = await esbuild.context(buildOpts);
  await context.watch();
}
