// 中文→英文食材映射表 (由 menu-calculator.ts 提取)
// v2.05 最终版: ~230 条词条

export const FOOD_CN_MAP: Record<string, string> = {
    '牛肉': 'beef', '猪肉': 'pork', '鸡肉': 'chicken', '鸡蛋': 'egg',
    '鸡': 'chicken', '鱼': 'fish', '虾': 'shrimp', '羊肉': 'lamb',
    '鸭肉': 'duck', '鹅肉': 'goose', '兔肉': 'rabbit', '猪肝': 'pork liver',
    '鸡胸肉': 'chicken breast', '鸡腿': 'chicken leg', '牛排': 'beef steak',
    '培根': 'bacon', '火腿': 'ham', '香肠': 'sausage',
    '牛腩': 'beef brisket', '肥牛': 'beef', '牛里脊': 'beef tenderloin',
    '五花肉': 'pork belly', '猪里脊': 'pork tenderloin', '排骨': 'pork ribs',
    '猪蹄': 'pork trotters', '瘦肉': 'pork, lean', '肉末': 'ground meat',
    '鸡翅': 'chicken wing', '鸭腿': 'duck leg', '鸽子': 'squab',
    '午餐肉': 'luncheon meat', '腊肉': 'cured pork', '牛肉丸': 'meatball',
    // 海鲜水产
    '三文鱼': 'salmon', '金枪鱼': 'tuna', '鳕鱼': 'cod', '带鱼': 'hairtail',
    '螃蟹': 'crab', '龙虾': 'lobster', '贝类': 'shellfish', '蛤蜊': 'clam',
    '牡蛎': 'oyster', '扇贝': 'scallop', '鱿鱼': 'squid', '章鱼': 'octopus',
    '小龙虾': 'crawfish', '基围虾': 'shrimp', '鲍鱼': 'abalone', '海参': 'sea cucumber',
    '海带': 'kelp', '紫菜': 'seaweed', '多宝鱼': 'flatfish', '鲈鱼': 'sea bass', '生蚝': 'oyster',
    // 主食与面点
    '米饭': 'rice, cooked', '大米': 'rice', '面粉': 'flour', '面条': 'noodles',
    '馒头': 'steamed bun', '面包': 'bread', '燕麦': 'oats', '玉米': 'corn',
    '小米': 'millet', '糙米': 'brown rice', '红薯': 'sweet potato',
    '土豆': 'potato', '芋头': 'taro', '山药': 'yam',
    '炒饭': 'fried rice', '白粥': 'rice congee', '稀饭': 'rice gruel',
    '水饺': 'dumpling', '饺子': 'dumpling', '包子': 'steamed stuffed bun', '馄饨': 'wonton',
    '油条': 'fried dough stick', '烧饼': 'flatbread', '手抓饼': 'pancake',
    '全麦面包': 'whole wheat bread', '吐司': 'toast', '意面': 'spaghetti',
    '粉丝': 'cellophane noodles', '米粉': 'rice noodles', '燕麦片': 'oatmeal',
    // 蔬菜与菌菇
    '西红柿': 'tomato', '番茄': 'tomato', '胡萝卜': 'carrot',
    '白菜': 'cabbage', '菠菜': 'spinach', '洋葱': 'onion', '大蒜': 'garlic',
    '姜': 'ginger', '蘑菇': 'mushroom', '青椒': 'green pepper',
    '黄瓜': 'cucumber', '茄子': 'eggplant', '西兰花': 'broccoli',
    '花菜': 'cauliflower', '芹菜': 'celery', '生菜': 'lettuce',
    '韭菜': 'chives', '蒜苗': 'garlic sprouts', '豆芽': 'bean sprouts',
    '南瓜': 'pumpkin', '冬瓜': 'winter melon', '丝瓜': 'loofah',
    '苦瓜': 'bitter melon', '莲藕': 'lotus root', '竹笋': 'bamboo shoots',
    '油菜': 'rapeseed green', '上海青': 'bok choy', '小白菜': 'baby bok choy',
    '空心菜': 'water spinach', '芦笋': 'asparagus', '秋葵': 'okra',
    '娃娃菜': 'baby cabbage', '茼蒿': 'chrysanthemum greens', '油麦菜': 'romaine lettuce',
    '紫甘蓝': 'red cabbage', '海鲜菇': 'beech mushroom', '茶树菇': 'tea tree mushroom',
    // 水果
    '苹果': 'apple', '香蕉': 'banana', '橙子': 'orange', '柠檬': 'lemon',
    '葡萄': 'grape', '草莓': 'strawberry', '蓝莓': 'blueberry',
    '西瓜': 'watermelon', '哈密瓜': 'cantaloupe', '桃子': 'peach',
    '梨': 'pear', '芒果': 'mango', '菠萝': 'pineapple', '猕猴桃': 'kiwi',
    '樱桃': 'cherry', '荔枝': 'lychee', '龙眼': 'longan', '牛油果': 'avocado',
    // 豆制品与坚果
    '豆腐': 'tofu', '黄豆': 'soybean', '绿豆': 'mung bean', '红豆': 'red bean',
    '黑豆': 'black bean', '豌豆': 'pea', '花生': 'peanut',
    '核桃': 'walnut', '杏仁': 'almond', '腰果': 'cashew',
    '芝麻': 'sesame', '葵花籽': 'sunflower seed',
    '豆浆': 'soy milk', '豆腐干': 'dried tofu', '腐竹': 'tofu skin',
    '千张': 'tofu skin sheet', '素鸡': 'vegetarian chicken', '冻豆腐': 'frozen tofu',
    // 乳制品与饮品
    '牛奶': 'milk', '酸奶': 'yogurt', '奶酪': 'cheese', '黄油': 'butter',
    '奶油': 'cream', '脱脂牛奶': 'skim milk', '全脂牛奶': 'whole milk',
    '咖啡': 'coffee', '奶茶': 'milk tea', '绿茶': 'green tea', '红茶': 'black tea',
    // 调味料与干货
    '菜籽油': 'oil, canola', '酱油': 'soy sauce', '盐': 'salt', '糖': 'sugar',
    '胡椒': 'pepper', '醋': 'vinegar', '蜂蜜': 'honey', '橄榄油': 'olive oil',
    '花椒': 'sichuan pepper', '八角': 'star anise', '桂皮': 'cinnamon',
    '黑木耳': 'wood ear', '银耳': 'white fungus', '香菇': 'shiitake',
    '金针菇': 'enoki mushroom', '杏鲍菇': 'king oyster mushroom', '芝麻油': 'sesame oil',
    // v2.04 巡检补充: 132 条高频未匹配词条
    '巴沙鱼': 'fish', '黑鳕鱼': 'cod', '肉蟹': 'crab', '肋排': 'pork ribs',
    '鸡腿肉': 'chicken leg', '鸡全翅': 'chicken wing', '新鲜鸡翅': 'chicken wing',
    '猪肉末': 'ground pork', '瘦肉末': 'ground pork', '碎牛肉': 'ground beef',
    '肉馅': 'ground meat', '带皮五花肉': 'pork belly', '五花肉薄片': 'pork belly',
    '猪油渣': 'pork fat', '咸肉': 'cured pork', '大排': 'pork ribs',
    '鳝丝': 'eel', '虾仁': 'shrimp',
    '生抽': 'soy sauce', '老抽': 'soy sauce', '生抽酱油': 'soy sauce',
    '蚝油': 'oyster sauce', '陈醋': 'vinegar', '味淋': 'cooking wine',
    '黄豆酱': 'soybean paste', '豆瓣酱': 'bean paste', '郫县豆瓣酱': 'bean paste',
    '红油豆瓣酱': 'bean paste', '甜面酱': 'sweet bean paste', '海鲜酱': 'hoisin sauce',
    '番茄酱': 'ketchup', '番茄膏': 'tomato paste', '蛋黄酱': 'mayonnaise',
    '香叶': 'bay leaf', '孜然粉': 'cumin', '孜然籽': 'cumin seed',
    '干辣椒': 'chili pepper', '小米椒': 'chili pepper', '小米辣': 'chili pepper',
    '朝天椒': 'chili pepper', '红尖椒': 'chili pepper',
    '红椒': 'red pepper', '青辣椒': 'green chili', '线椒': 'chili pepper',
    '白胡椒粉': 'white pepper', '黑胡椒': 'black pepper', '黑胡椒粉': 'black pepper',
    '黑胡椒粒': 'black pepper', '黑椒碎': 'black pepper', '黑椒粉': 'black pepper',
    '花椒油': 'pepper oil', '藤椒油': 'pepper oil',
    '青花椒': 'sichuan pepper', '姜黄粉': 'turmeric', '甜椒粉': 'paprika',
    '红辣椒粉': 'chili powder', '辣椒粉': 'chili powder', '芥末油': 'mustard oil',
    '蒜瓣': 'garlic', '蒜末': 'garlic', '蒜粉': 'garlic', '蒜蓉': 'garlic',
    '姜末': 'ginger', '姜片': 'ginger', '老姜': 'ginger', '生姜末': 'ginger',
    '葱花': 'scallion', '小葱': 'scallion', '小葱花': 'scallion',
    '青葱': 'scallion', '葱白': 'scallion', '葱末': 'scallion', '葱结': 'scallion',
    '白芝麻': 'sesame seed', '芝麻香油': 'sesame oil',
    '中筋面粉': 'all-purpose flour', '玉米淀粉': 'corn starch', '土豆淀粉': 'potato starch',
    '吉士粉': 'custard powder', '泡打粉': 'baking powder', '干酵母': 'yeast',
    '小苏打': 'baking soda',
    '红枣': 'jujube', '枸杞': 'goji berry', '莲子': 'lotus seed',
    '桂圆': 'longan', '薏米': 'coix seed',
    '花生碎': 'peanut', '松子仁': 'pine nut', '奇亚籽': 'chia seed', '葡萄干': 'raisin',
    '椰奶': 'coconut milk', '淡奶油': 'cream', '酥油': 'ghee',
    '芝士片': 'cheese', '原味酸奶': 'yogurt', '奶粉': 'milk powder',
    '内酯豆腐': 'tofu', '老豆腐': 'tofu', '日本豆腐': 'tofu',
    '花卷': 'steamed roll', '烧卖皮': 'wonton wrapper',
    '红薯粉丝': 'sweet potato noodle', '干面条': 'noodles',
    '半干荞麦面': 'buckwheat noodle', '泡面': 'instant noodle', '方便面': 'instant noodle',
    '年糕': 'rice cake',
    '包菜': 'cabbage', '韭黄': 'yellow chive', '瓠瓜': 'bottle gourd',
    '马铃薯': 'potato', '毛豆': 'edamame', '蚕豆': 'broad bean',
    '鹰嘴豆': 'chickpea', '干鹰嘴豆': 'chickpea', '鹰嘴豆粉': 'chickpea flour',
    '红腰豆': 'kidney bean', '干红芸豆': 'kidney bean',
    '火腿肠': 'ham sausage', '红肠': 'sausage', '腊肠': 'chinese sausage',
    '月桂叶': 'bay leaf', '薄荷叶': 'mint', '欧芹': 'parsley',
    '肉桂棒': 'cinnamon', '小豆蔻': 'cardamom', '小豆蔻粉': 'cardamom',
    '丁香': 'clove', '茴香': 'fennel',
    '五香粉': 'five spice', '十三香': 'five spice',
    // v2.04 第三轮补映射: 巡检剩余的生鲜干货 + 特色食材
    '开洋': 'dried shrimp', '阳江豆豉': 'fermented black bean',
    '红腐乳': 'fermented tofu', '腐乳汁': 'fermented tofu',
    '红泡椒': 'pickled chili', '火锅底料': 'hot pot base',
    '皮冻': 'pork skin jelly', '冬笋': 'bamboo shoot',
    '巴斯马蒂香米': 'basmati rice',
    '印度综合香料粉': 'garam masala', '干葫芦巴叶': 'fenugreek leaf',
    '石榴粉': 'pomegranate powder',
    '复配食品增稠剂': 'thickener',
    '冷冻花卷': 'steamed bun', '西洋参': 'ginseng',
    '石斛': 'dendrobium', '玉竹': 'solomon seal', '麦冬': 'ophiopogon',
    '美人椒': 'chili pepper',
};

export type FoodCnMap = typeof FOOD_CN_MAP;
